# Import Libraries

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

# Give File Path and Read File

In [4]:
path = r"C:\Users\TALIYEVA\01_Project_Data_Analysts_Survey\Survey_Dataset.xlsx"

In [5]:
df = pd.read_excel(path)

# Set to Visualize all rows and columns

In [6]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [7]:
df

                    Unique ID      Email Date Taken (America/New_York)  \
0    62a33b3db4da29969c62df3d  anonymous                     6/10/2022
1    62a33ba1bae91e4b8b82e35c  anonymous                     6/10/2022
2    62a33c2cbc6861bf3176bec1  anonymous                     6/10/2022
3    62a33c8624a26260273822f9  anonymous                     6/10/2022
4    62a33c91f3072dd892621e03  anonymous                     6/10/2022
5    62a33cb6cf25554317300177  anonymous                     6/10/2022
6    62a33cb72e54c9003e531c65  anonymous                     6/10/2022
7    62a33cd30f8c8599d5af0f8f  anonymous                     6/10/2022
8    62a33cd3cf255543173001d9  anonymous                     6/10/2022
9    62a33cd8bc6861bf3176c05f  anonymous                     6/10/2022
10   62a33ce918134ddc75ce8c30  anonymous                     6/10/2022
11   62a33cf30a77c1a77f65baa2  anonymous                     6/10/2022
12   62a33d15f408bae018ed370d  anonymous                     6/10/2022
13   62a33d1ebae91e4b8b82e707  anonymous                     6/10/2022
14   62a33d4624a26260273824c4  anonymous                     6/10/2022
15   62a33d5c0f8c8599d5af107c  anonymous                     6/10/2022
16   62a33d850f8c8599d5af10cb  anonymous                     6/10/2022
17   62a33d9bf8f7561645852496  anonymous                     6/10/2022
18   62a33dbdd8c00e9f5419cd65  anonymous                     6/10/2022
19   62a33de124a26260273826b2  anonymous                     6/10/2022
20   62a33dedd8c00e9f5419ce2b  anonymous                     6/10/2022
21   62a33dfbd8c00e9f5419ceda  anonymous                     6/10/2022
22   62a33e38f3072dd8926221d3  anonymous                     6/10/2022
23   62a33e54d8c00e9f5419cfe9  anonymous                     6/10/2022
24   62a33e62575fa3a5ae88aabf  anonymous                     6/10/2022
25   62a33e63cec54911e9ca4f99  anonymous                     6/10/2022
26   62a33e72bae91e4b8b82ea1a  anonymous                     6/10/2022
27   62a33e890f8c8599d5af13b9  anonymous                     6/10/2022
28   62a33e8bf8d5efcc22f7c79a  anonymous                     6/10/2022
29   62a33e90cec54911e9ca5031  anonymous                     6/10/2022
30   62a33e9df8f756164585277b  anonymous                     6/10/2022
31   62a33eb6bc6861bf3176c5a3  anonymous                     6/10/2022
32   62a33ee0bae91e4b8b82eaec  anonymous                     6/10/2022
33   62a33ee80f8c8599d5af14b7  anonymous                     6/10/2022
34   62a33efe0a77c1a77f65bf1e  anonymous                     6/10/2022
35   62a33f0ef408bae018ed3aeb  anonymous                     6/10/2022
36   62a33f17f8f7561645852867  anonymous                     6/10/2022
37   62a33f52bc6861bf3176c72c  anonymous                     6/10/2022
38   62a33f56cf255543173005e9  anonymous                     6/10/2022
39   62a33f5a5d257a28a30d7bb5  anonymous                     6/10/2022
40   62a33fa5cec54911e9ca51f1  anonymous                     6/10/2022
41   62a33fcb575fa3a5ae88ad59  anonymous                     6/10/2022
42   62a33fcf18134ddc75ce91c3  anonymous                     6/10/2022
43   62a34006d8c00e9f5419d341  anonymous                     6/10/2022
44   62a34020575fa3a5ae88ade0  anonymous                     6/10/2022
45   62a34038b4da29969c62eafe  anonymous                     6/10/2022
46   62a3406b575fa3a5ae88ae78  anonymous                     6/10/2022
47   62a340cab4da29969c62ec01  anonymous                     6/10/2022
48   62a340d62e54c9003e5324b4  anonymous                     6/10/2022
49   62a340e10a77c1a77f65c2e7  anonymous                     6/10/2022
50   62a340f5bc6861bf3176caa4  anonymous                     6/10/2022
51   62a34117cec54911e9ca54e7  anonymous                     6/10/2022
52   62a3413a5d257a28a30d8074  anonymous                     6/10/2022
53   62a341a1f3072dd8926229a5  anonymous                     6/10/2022
54   62a341b0f8f7561645852d1d  anonymous                     6/10/2022
55   62a341e8f8d5efcc22f7d002  anonymous                     6/10/2022
56   62a34210cf25554317300c02  anonymous                     6/10/2022
57   62a3424eb4da29969c62eedd  anonymous                     6/10/2022
58   62a34256bae91e4b8b82f16d  anonymous                     6/10/2022
59   62a3426cf408bae018ed409b  anonymous                     6/10/2022
60   62a34272f8d5efcc22f7d15f  anonymous                     6/10/2022
61   62a34340bc6861bf3176d05b  anonymous                     6/10/2022
62   62a34383b4da29969c62f1be  anonymous                     6/10/2022
63   62a34389cec54911e9ca5a22  anonymous                     6/10/2022
64   62a343a22e54c9003e532a2a  anonymous                     6/10/2022
65   62a343d9f3072dd892622fe4  anonymous                     6/10/2022
66   62a34400d8c00e9f5419dc2b  anonymous                     6/10/2022
67   62a34425f8d5efcc22f7d525  anonymous                     6/10/2022
68   62a34449575fa3a5ae88b637  anonymous                     6/10/2022
69   62a3445dcf255543173011e1  anonymous                     6/10/2022
70   62a3447a575fa3a5ae88b6c0  anonymous                     6/10/2022
71   62a3449f7dc029e2d66bf5d1  anonymous                     6/10/2022
72   62a344c5f408bae018ed4806  anonymous                     6/10/2022
73   62a344c6f8d5efcc22f7d6e1  anonymous                     6/10/2022
74   62a344e1f3072dd892623328  anonymous                     6/10/2022
75   62a3450424a262602738357f  anonymous                     6/10/2022
76   62a3452818134ddc75ce9e1b  anonymous                     6/10/2022
77   62a345490a77c1a77f65cc5b  anonymous                     6/10/2022
78   62a3455bbc6861bf3176d57a  anonymous                     6/10/2022
79   62a3457bf8d5efcc22f7da17  anonymous                     6/10/2022
80   62a345b2bae91e4b8b82fad6  anonymous                     6/10/2022
81   62a345c47dc029e2d66bf80a  anonymous                     6/10/2022
82   62a345e25d257a28a30d8b43  anonymous                     6/10/2022
83   62a34646f8d5efcc22f7dc5c  anonymous                     6/10/2022
84   62a34687f408bae018ed4c52  anonymous                     6/10/2022
85   62a346a37dc029e2d66bfa6d  anonymous                     6/10/2022
86   62a346a95d257a28a30d8cb9  anonymous                     6/10/2022
87   62a346b4bc6861bf3176d7ce  anonymous                     6/10/2022
88   62a346cef8f756164585385b  anonymous                     6/10/2022
89   62a346d724a2626027383abd  anonymous                     6/10/2022
90   62a346d90a77c1a77f65d08d  anonymous                     6/10/2022
91   62a34726f8d5efcc22f7dec7  anonymous                     6/10/2022
92   62a3476c5d257a28a30d8e6d  anonymous                     6/10/2022
93   62a347b4f8f7561645853a98  anonymous                     6/10/2022
94   62a347f6b4da29969c62fb79  anonymous                     6/10/2022
95   62a3483018134ddc75cea4e6  anonymous                     6/10/2022
96   62a348650f8c8599d5af2b77  anonymous                     6/10/2022
97   62a3489318134ddc75cea659  anonymous                     6/10/2022
98   62a348bf2e54c9003e533634  anonymous                     6/10/2022
99   62a348c2f3072dd892623c10  anonymous                     6/10/2022
100  62a348f2f8d5efcc22f7e2ba  anonymous                     6/10/2022
101  62a349160a77c1a77f65d4db  anonymous                     6/10/2022
102  62a3493fb4da29969c62fe63  anonymous                     6/10/2022
103  62a3496e575fa3a5ae88c4e6  anonymous                     6/10/2022
104  62a3498e575fa3a5ae88c554  anonymous                     6/10/2022
105  62a34991b4da29969c62ff4b  anonymous                     6/10/2022
106  62a349bbf8f756164585400d  anonymous                     6/10/2022
107  62a349c7cec54911e9ca67c7  anonymous                     6/10/2022
108  62a349d5d8c00e9f5419ead2  anonymous                     6/10/2022
109  62a349e6b4da29969c63000c  anonymous                     6/10/2022
110  62a34a03cec54911e9ca6869  anonymous                     6/10/2022
111  62a34ab15d257a28a30d9589  anonymous                     6/10/2022
112  62a34abc0f8c8599d5af31c5  anonymous                     6/10/2022
113  62a34b07cec54911e9ca6b6e  anonymous                     6/10/2022
114  62a34b0eb4da29969c6302ce  anonymous                     6/10/2022
115  62a34b1b0f8c8599d5af328b  anonymous                     6/10/2022
116  62a34b5b5d257a28a30d96a6  anonymous                     6/10/2022
117  62a34b7ebae91e4b8b83076c  anonymous                     6/10/2022
118  62a34b99cec54911e9ca6e14  anonymous                     6/10/2022
119  62a34bb0f3072dd892624210  anonymous                     6/10/2022
120  62a34bd0cf2555431730208b  anonymous                     6/10/2022
121  62a34bd4f408bae018ed57bd  anonymous                     6/10/2022
122  62a34c66b4da29969c6305af  anonymous                     6/10/2022
123  62a34d1ff8f756164585465c  anonymous                     6/10/2022
124  62a34d4118134ddc75ceb0ed  anonymous                     6/10/2022
125  62a34da0f408bae018ed5abd  anonymous                     6/10/2022
126  62a34dbb5d257a28a30d9a61  anonymous                     6/10/2022
127  62a34e00f8f7561645854954  anonymous                     6/10/2022
128  62a34e082e54c9003e534118  anonymous                     6/10/2022
129  62a34eb7bc6861bf3176e6d8  anonymous                     6/10/2022
130  62a34f2af8f7561645854c1c  anonymous                     6/10/2022
131  62a34f3bf408bae018ed5e42  anonymous                     6/10/2022
132  62a34fa418134ddc75ceb509  anonymous                     6/10/2022
133  62a34fbacec54911e9ca776f  anonymous                     6/10/2022
134  62a34fc3f3072dd892624a45  anonymous                     6/10/2022
135  62a34ff1f408bae018ed601d  anonymous                     6/10/2022
136  62a34ff4f3072dd892624b32  anonymous                     6/10/2022
137  62a3505bd8c00e9f5419f8df  anonymous                     6/10/2022
138  62a350f7f3072dd892624d05  anonymous                     6/10/2022
139  62a35130f3072dd892624d9f  anonymous                     6/10/2022
140  62a351860a77c1a77f65e86b  anonymous                     6/10/2022
141  62a3519b24a262602738514a  anonymous                     6/10/2022
142  62a35236b4da29969c631214  anonymous                     6/10/2022
143  62a352a32e54c9003e534981  anonymous                     6/10/2022
144  62a352f00a77c1a77f65eae7  anonymous                     6/10/2022
145  62a353372e54c9003e534a40  anonymous                     6/10/2022
146  62a353565d257a28a30da59f  anonymous                     6/10/2022
147  62a353f07dc029e2d66c1783  anonymous                     6/10/2022
148  62a3545e0f8c8599d5af474b  anonymous                     6/10/2022
149  62a35472cec54911e9ca82bc  anonymous                     6/10/2022
150  62a354bdb4da29969c631700  anonymous                     6/10/2022
151  62a354e9cf255543173031ed  anonymous                     6/10/2022
152  62a35541f3072dd892625517  anonymous                     6/10/2022
153  62a355445d257a28a30dab12  anonymous                     6/10/2022
154  62a35631cf25554317303425  anonymous                     6/10/2022
155  62a357390a77c1a77f65f189  anonymous                     6/10/2022
156  62a3578b0a77c1a77f65f279  anonymous                     6/10/2022
157  62a357d30f8c8599d5af4ea3  anonymous                     6/10/2022
158  62a3582e575fa3a5ae88e506  anonymous                     6/10/2022
159  62a35878575fa3a5ae88e5d5  anonymous                     6/10/2022
160  62a35981bae91e4b8b8323dd  anonymous                     6/10/2022
161  62a35a2c7dc029e2d66c2519  anonymous                     6/10/2022
162  62a35aa2f8d5efcc22f8075d  anonymous                     6/10/2022
163  62a35ababae91e4b8b83269d  anonymous                     6/10/2022
164  62a35ae0575fa3a5ae88ea98  anonymous                     6/10/2022
165  62a35ae87dc029e2d66c279b  anonymous                     6/10/2022
166  62a35b13bc6861bf31770188  anonymous                     6/10/2022
167  62a35b72f408bae018ed76a8  anonymous                     6/10/2022
168  62a35b965d257a28a30db899  anonymous                     6/10/2022
169  62a35ba3f3072dd892626068  anonymous                     6/10/2022
170  62a35c890a77c1a77f65fdfa  anonymous                     6/10/2022
171  62a35d8f575fa3a5ae88efd6  anonymous                     6/10/2022
172  62a35d95cf25554317304386  anonymous                     6/10/2022
173  62a35e970a77c1a77f66035a  anonymous                     6/10/2022
174  62a35eabf408bae018ed7cbc  anonymous                     6/10/2022
175  62a35f0d24a2626027386a8b  anonymous                     6/10/2022
176  62a35f825d257a28a30dc128  anonymous                     6/10/2022
177  62a35fa0f8f7561645856c35  anonymous                     6/10/2022
178  62a35fc1f8f7561645856c98  anonymous                     6/10/2022
179  62a3602318134ddc75ced6b9  anonymous                     6/10/2022
180  62a360b8f8f7561645856ec4  anonymous                     6/10/2022
181  62a360dbd8c00e9f541a16cf  anonymous                     6/10/2022
182  62a36146f8f7561645856ff7  anonymous                     6/10/2022
183  62a361af0f8c8599d5af6277  anonymous                     6/10/2022
184  62a361cc575fa3a5ae88f908  anonymous                     6/10/2022
185  62a3620f0f8c8599d5af63a5  anonymous                     6/10/2022
186  62a36251d8c00e9f541a199e  anonymous                     6/10/2022
187  62a36275bc6861bf31771183  anonymous                     6/10/2022
188  62a3636c2e54c9003e536e6b  anonymous                     6/10/2022
189  62a365c2f8d5efcc22f81e2e  anonymous                     6/10/2022
190  62a365d5d8c00e9f541a20cf  anonymous                     6/10/2022
191  62a3670b575fa3a5ae890422  anonymous                     6/10/2022
192  62a3676bb4da29969c633ac7  anonymous                     6/10/2022
193  62a36794b4da29969c633b48  anonymous                     6/10/2022
194  62a367d224a2626027387b56  anonymous                     6/10/2022
195  62a367ed18134ddc75cee697  anonymous                     6/10/2022
196  62a36802f8f7561645857e38  anonymous                     6/10/2022
197  62a3684ebc6861bf31771f15  anonymous                     6/10/2022
198  62a3688df8f7561645857f7e  anonymous                     6/10/2022
199  62a368ee2e54c9003e537e4a  anonymous                     6/10/2022
200  62a369280a77c1a77f661ad0  anonymous                     6/10/2022
201  62a36969f8f756164585821d  anonymous                     6/10/2022
202  62a3697ff408bae018ed948b  anonymous                     6/10/2022
203  62a36ac6cf255543173063d8  anonymous                     6/10/2022
204  62a36ad1f408bae018ed9793  anonymous                     6/10/2022
205  62a36b6c24a26260273882a2  anonymous                     6/10/2022
206  62a36b862e54c9003e5383c6  anonymous                     6/10/2022
207  62a36d12f8d5efcc22f82cd8  anonymous                     6/10/2022
208  62a36d3124a262602738862c  anonymous                     6/10/2022
209  62a36e470a77c1a77f662470  anonymous                     6/10/2022
210  62a36e7024a262602738890a  anonymous                     6/10/2022
211  62a36fe67dc029e2d66c5303  anonymous                     6/10/2022
212  62a3701f575fa3a5ae89164e  anonymous                     6/10/2022
213  62a370635d257a28a30de5eb  anonymous                     6/10/2022
214  62a37128d8c00e9f541a39dd  anonymous                     6/10/2022
215  62a3715124a2626027388f02  anonymous                     6/10/2022
216  62a37222cf2555431730732d  anonymous                     6/10/2022
217  62a373efbc6861bf3177360b  anonymous                     6/10/2022
218  62a3759e5d257a28a30def3a  anonymous                     6/10/2022
219  62a3777624a262602738997e  anonymous                     6/10/2022
220  62a377987dc029e2d66c638d  anonymous                     6/10/2022
221  62a377f424a2626027389af3  anonymous                     6/10/2022
222  62a3784c0f8c8599d5af8fbc  anonymous                     6/10/2022
223  62a37a43d8c00e9f541a4a7c  anonymous                     6/10/2022
224  62a37a7818134ddc75cf0d4c  anonymous                     6/10/2022
225  62a37aa1cf255543173081e5  anonymous                     6/10/2022
226  62a37ad924a2626027389f8a  anonymous                     6/10/2022
227  62a37b7db4da29969c636123  anonymous                     6/10/2022
228  62a37bab2e54c9003e53a10a  anonymous                     6/10/2022
229  62a37c50cec54911e9cacee2  anonymous                     6/10/2022
230  62a37d41bae91e4b8b8369f7  anonymous                     6/10/2022
231  62a37f8db4da29969c6367bf  anonymous                     6/10/2022
232  62a37ff3bae91e4b8b836ed0  anonymous                     6/10/2022
233  62a38023575fa3a5ae89339e  anonymous                     6/10/2022
234  62a38153cec54911e9cad855  anonymous                     6/10/2022
235  62a381d024a262602738ab19  anonymous                     6/10/2022
236  62a38227bae91e4b8b837235  anonymous                     6/10/2022
237  62a38489cf25554317309145  anonymous                     6/10/2022
238  62a384f0cec54911e9cadd6f  anonymous                     6/10/2022
239  62a385480f8c8599d5afa5c6  anonymous                     6/10/2022
240  62a3856218134ddc75cf1ee0  anonymous                     6/10/2022
241  62a385c40f8c8599d5afa6cf  anonymous                     6/10/2022
242  62a385ddbae91e4b8b837855  anonymous                     6/10/2022
243  62a385e7b4da29969c6372ab  anonymous                     6/10/2022
244  62a386dfcec54911e9cae1d3  anonymous                     6/10/2022
245  62a3870bbc6861bf31775841  anonymous                     6/10/2022
246  62a38733f8d5efcc22f859fc  anonymous                     6/10/2022
247  62a387e6575fa3a5ae8940a1  anonymous                     6/10/2022
248  62a388d524a262602738b869  anonymous                     6/10/2022
249  62a38975b4da29969c637830  anonymous                     6/10/2022
250  62a38985f8f756164585b89c  anonymous                     6/10/2022
251  62a389b70f8c8599d5afad1a  anonymous                     6/10/2022
252  62a389ed18134ddc75cf24f8  anonymous                     6/10/2022
253  62a38a060a77c1a77f6654b7  anonymous                     6/10/2022
254  62a38a4d575fa3a5ae8944df  anonymous                     6/10/2022
255  62a38a97cf25554317309af2  anonymous                     6/10/2022
256  62a38c120f8c8599d5afb0e9  anonymous                     6/10/2022
257  62a38c9dbc6861bf317760c4  anonymous                     6/10/2022
258  62a38de50f8c8599d5afb3e7  anonymous                     6/10/2022
259  62a3906224a262602738c58a  anonymous                     6/10/2022
260  62a3907cbae91e4b8b838917  anonymous                     6/10/2022
261  62a390c0d8c00e9f541a6fd7  anonymous                     6/10/2022
262  62a390e4f3072dd89262c0cd  anonymous                     6/10/2022
263  62a391cacf2555431730a623  anonymous                     6/10/2022
264  62a39214f8f756164585c6b6  anonymous                     6/10/2022
265  62a39297b4da29969c638679  anonymous                     6/10/2022
266  62a393330a77c1a77f6662e4  anonymous                     6/10/2022
267  62a3944024a262602738cb07  anonymous                     6/10/2022
268  62a3951ed8c00e9f541a75d1  anonymous                     6/10/2022
269  62a3958fcec54911e9caf827  anonymous                     6/10/2022
270  62a3970ebae91e4b8b839495  anonymous                     6/10/2022
271  62a3976ecf2555431730af5e  anonymous                     6/10/2022
272  62a397fb5d257a28a30e279a  anonymous                     6/10/2022
273  62a3980c7dc029e2d66c9a81  anonymous                     6/10/2022
274  62a3980e0f8c8599d5afc32c  anonymous                     6/10/2022
275  62a39a340f8c8599d5afc6ce  anonymous                     6/10/2022
276  62a39a95bc6861bf3177751d  anonymous                     6/10/2022
277  62a39b315d257a28a30e2cae  anonymous                     6/10/2022
278  62a39b6cf408bae018ede929  anonymous                     6/10/2022
279  62a39bd324a262602738d725  anonymous                     6/10/2022

# Perform simple EDA

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 28 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Unique ID                                                                                     630 non-null    object
 1   Email                                                                                         630 non-null    object
 2   Date Taken (America/New_York)                                                                 630 non-null    object
 3   Time Taken (America/New_York)                                                                 630 non-null    object
 4   Browser                                                                                       0 non-null      float64
 5   OS                                                                                            0 non-null      float64
 6   City                                                                                          0 non-null      float64
 7   Country                                                                                       0 non-null      float64
 8   Referrer                                                                                      0 non-null      float64
 9   Time Spent                                                                                    630 non-null    object
 10  Q1 - Which Title Best Fits your Current Role?                                                 630 non-null    object
 11  Q2 - Did you switch careers into Data?                                                        630 non-null    object
 12  Q3 - Current Yearly Salary (in USD)                                                           630 non-null    object
 13  Q4 - What Industry do you work in?                                                            630 non-null    object
 14  Q5 - Favorite Programming Language                                                            630 non-null    object
 15  Q6 - How Happy are you in your Current Position with the following? (Salary)                  623 non-null    float64
 16  Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)       620 non-null    float64
 17  Q6 - How Happy are you in your Current Position with the following? (Coworkers)               619 non-null    float64
 18  Q6 - How Happy are you in your Current Position with the following? (Management)              618 non-null    float64
 19  Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)         617 non-null    float64
 20  Q6 - How Happy are you in your Current Position with the following? (Learning New Things)     625 non-null    float64
 21  Q7 - How difficult was it for you to break into Data?                                         630 non-null    object
 22  Q8 - If you were to look for a new job today, what would be the most important thing to you?  630 non-null    object
 23  Q9 - Male/Female?                                                                             630 non-null    object
 24  Q10 - Current Age                                                                             630 non-null    int64
 25  Q11 - Which Country do you live in?                                                           630 non-null    object
 26  Q12 - Highest Level of Education                                                              578 non-null    object
 27  Q13 - Ethnicity                                                                               630 non-null    object
dtypes: float64(11), int64(1), object(16)
memory usage: 137.9+ KB

In [9]:
df.describe()

,Browser,OS,City,Country,Referrer,Q6 - How Happy are you in your Current Position with the following? (Salary),Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance),Q6 - How Happy are you in your Current Position with the following? (Coworkers),Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q10 - Current Age
count,0.0,0.0,0.0,0.0,0.0,623.000000,620.000000,619.000000,618.000000,617.000000,625.000000,630.000000
mean,NaN,NaN,NaN,NaN,NaN,4.269663,5.741935,5.861066,5.326861,4.756888,5.608000,29.866667
std,NaN,NaN,NaN,NaN,NaN,2.772945,2.761584,2.703244,2.738161,2.820822,3.006659,7.245941
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
25%,NaN,NaN,NaN,NaN,NaN,2.000000,4.000000,4.000000,4.000000,3.000000,3.000000,25.000000
50%,NaN,NaN,NaN,NaN,NaN,4.000000,6.000000,6.000000,5.000000,5.000000,6.000000,28.000000
75%,NaN,NaN,NaN,NaN,NaN,7.000000,8.000000,8.000000,7.000000,7.000000,8.000000,33.000000
max,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,92.000000

# Remove & Rename Columns

In [10]:
columns_to_drop = ['Q13 - Ethnicity', 'Q8 - If you were to look for a new job today, what would be the most important thing to you?', 'Q7 - How difficult was it for you to break into Data?', 'Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)', 'Email', 'Referrer', 'Time Taken (America/New_York)', 'Browser', 'OS', 'City', 'Country']
df = df.drop(columns=columns_to_drop, axis = 1)

In [11]:
new_column_names = {'Q1 - Which Title Best Fits your Current Role?':'Job Title', 'Q2 - Did you switch careers into Data?':'Career Switch to Data', 'Q3 - Current Yearly Salary (in USD)':'Annual Salary (USD)', 'Q4 - What Industry do you work in?':'Working Industry', 'Q5 - Favorite Programming Language':'Favorite Programming Language', 'Q6 - How Happy are you in your Current Position with the following? (Salary)':'Happy with salary', 'Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)':'Happy with work-life balance', 'Q6 - How Happy are you in your Current Position with the following? (Coworkers)':'Happy with coworkers', 'Q6 - How Happy are you in your Current Position with the following? (Management)':'Happy with management', 'Q6 - How Happy are you in your Current Position with the following? (Learning New Things)':'Happy with learning opportunities', 'Q9 - Male/Female?':'Gender', 'Q10 - Current Age':'Age', 'Q11 - Which Country do you live in?':'Country', 'Q12 - Highest Level of Education':'Level of Education'}
df = df.rename(columns=new_column_names)

# Change Data Type

In [12]:
df['Date Taken (America/New_York)'] = pd.to_datetime(df['Date Taken (America/New_York)'])

In [13]:
df

,Unique ID,Date Taken (America/New_York),Time Spent,Job Title,Career Switch to Data,Annual Salary (USD),Working Industry,Favorite Programming Language,Happy with salary,Happy with work-life balance,Happy with coworkers,Happy with management,Happy with learning opportunities,Gender,Age,Country,Level of Education
0,62a33b3db4da29969c62df3d,2022-06-10,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,9.0,7.0,5.0,7.0,Male,26,United States,NaN
1,62a33ba1bae91e4b8b82e35c,2022-06-10,0:01:30,Data Analyst,No,41k-65k,Finance,R,1.0,2.0,5.0,2.0,3.0,Male,36,Canada,NaN
2,62a33c2cbc6861bf3176bec1,2022-06-10,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,0.0,8.0,7.0,5.0,7.0,Male,23,Other (Please Specify):Nigeria,NaN
3,62a33c8624a26260273822f9,2022-06-10,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,10.0,6.0,7.0,10.0,10.0,Female,35,Canada,NaN
4,62a33c91f3072dd892621e03,2022-06-10,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,1.0,4.0,4.0,4.0,1.0,Male,44,United States,NaN
5,62a33cb6cf25554317300177,2022-06-10,0:02:34,Data Analyst,Yes,0-40k,Other (Please Specify):Coworking space,Python,2.0,3.0,3.0,3.0,2.0,Male,33,Other (Please Specify):Republic democratic of ...,NaN
6,62a33cb72e54c9003e531c65,2022-06-10,0:01:15,Data Scientist,Yes,0-40k,Finance,Python,0.0,6.0,6.0,6.0,5.0,Male,24,Other (Please Specify),NaN
7,62a33cd30f8c8599d5af0f8f,2022-06-10,0:01:25,Data Engineer,Yes,125k-150k,Other (Please Specify):Retail,Other:SQL,10.0,5.0,5.0,5.0,9.0,Male,35,United States,NaN
8,62a33cd3cf255543173001d9,2022-06-10,0:02:10,Data Analyst,Yes,86k-105k,Healthcare,R,4.0,4.0,4.0,4.0,5.0,Male,35,United States,NaN
9,62a33cd8bc6861bf3176c05f,2022-06-10,0:01:27,Data Analyst,Yes,41k-65k,Telecommunication,Python,2.0,0.0,3.0,3.0,4.0,Male,28,United States,NaN
10,62a33ce918134ddc75ce8c30,2022-06-10,0:01:29,Data Analyst,Yes,66k-85k,Other (Please Specify):Logistics,Python,10.0,10.0,8.0,8.0,10.0,Male,37,Canada,NaN
11,62a33cf30a77c1a77f65baa2,2022-06-10,0:02:31,Data Analyst,Yes,0-40k,Other (Please Specify):Igaming,Python,3.0,8.0,10.0,10.0,8.0,Male,32,Other (Please Specify):Serbia,NaN
12,62a33d15f408bae018ed370d,2022-06-10,0:03:20,Data Analyst,Yes,0-40k,Tech,R,1.0,10.0,9.0,9.0,10.0,Male,34,Other (Please Specify):Argentina,NaN
13,62a33d1ebae91e4b8b82e707,2022-06-10,0:00:55,Data Scientist,Yes,0-40k,Education,Python,3.0,10.0,10.0,6.0,8.0,Male,30,United Kingdom,NaN
14,62a33d4624a26260273824c4,2022-06-10,0:01:24,Data Analyst,No,41k-65k,Construction,R,4.0,5.0,5.0,5.0,5.0,Male,31,United States,NaN
15,62a33d5c0f8c8599d5af107c,2022-06-10,0:00:47,Data Analyst,Yes,41k-65k,Finance,Python,4.0,10.0,7.0,7.0,5.0,Male,29,United States,NaN
16,62a33d850f8c8599d5af10cb,2022-06-10,0:01:06,Data Analyst,Yes,0-40k,Tech,Python,1.0,2.0,4.0,2.0,2.0,Male,22,Other (Please Specify):Niger,NaN
17,62a33d9bf8f7561645852496,2022-06-10,0:01:04,Student/Looking/None,Yes,0-40k,Other (Please Specify):Retail,Python,1.0,3.0,2.0,2.0,1.0,Male,23,United States,NaN
18,62a33dbdd8c00e9f5419cd65,2022-06-10,0:01:05,Student/Looking/None,No,41k-65k,Tech,R,7.0,8.0,8.0,6.0,3.0,Female,26,Canada,NaN
19,62a33de124a26260273826b2,2022-06-10,0:01:21,Data Analyst,No,0-40k,Other (Please Specify):Aviation,Python,1.0,1.0,1.0,1.0,0.0,Male,28,Other (Please Specify):Nigeria,NaN
20,62a33dedd8c00e9f5419ce2b,2022-06-10,0:01:23,Data Analyst,Yes,41k-65k,Finance,Python,5.0,5.0,5.0,5.0,5.0,Male,29,Other (Please Specify):Kenya,NaN
21,62a33dfbd8c00e9f5419ceda,2022-06-10,0:01:35,Data Analyst,Yes,106k-125k,Tech,Other:Mostly use sql but that’s not programmin...,10.0,5.0,10.0,6.0,10.0,Female,31,United States,NaN
22,62a33e38f3072dd8926221d3,2022-06-10,0:01:25,Data Analyst,Yes,0-40k,Healthcare,Python,5.0,6.0,8.0,8.0,1.0,Male,28,Other (Please Specify):Azerbaijan,NaN
23,62a33e54d8c00e9f5419cfe9,2022-06-10,0:01:47,Data Analyst,No,0-40k,Finance,Python,4.0,4.0,4.0,4.0,4.0,Male,32,Other (Please Specify):Argentina,NaN
24,62a33e62575fa3a5ae88aabf,2022-06-10,0:02:14,Data Analyst,No,0-40k,Tech,Python,7.0,8.0,8.0,8.0,8.0,Male,24,Other (Please Specify):Sudan,NaN
25,62a33e63cec54911e9ca4f99,2022-06-10,0:02:21,Data Analyst,No,0-40k,Tech,Python,4.0,6.0,6.0,6.0,7.0,Male,31,India,NaN
26,62a33e72bae91e4b8b82ea1a,2022-06-10,0:02:07,Data Analyst,No,66k-85k,Other (Please Specify):Insurance,Other:SQL,7.0,10.0,5.0,5.0,2.0,Male,23,United States,NaN
27,62a33e890f8c8599d5af13b9,2022-06-10,0:01:20,Data Analyst,Yes,106k-125k,Other (Please Specify):Energy,Python,1.0,6.0,9.0,1.0,2.0,Female,33,United States,NaN
28,62a33e8bf8d5efcc22f7c79a,2022-06-10,0:01:34,Data Analyst,No,86k-105k,Healthcare,Other:Qlik sense script,6.0,7.0,7.0,7.0,4.0,Male,43,United States,NaN
29,62a33e90cec54911e9ca5031,2022-06-10,0:01:34,Student/Looking/None,Yes,0-40k,Other (Please Specify):Oil and gas,R,0.0,0.0,5.0,0.0,0.0,Female,23,Other (Please Specify):Nigeria,NaN
30,62a33e9df8f756164585277b,2022-06-10,0:01:47,Student/Looking/None,Yes,41k-65k,Finance,Python,10.0,7.0,10.0,10.0,3.0,Male,31,United States,NaN
31,62a33eb6bc6861bf3176c5a3,2022-06-10,0:01:38,Data Analyst,Yes,66k-85k,Finance,Python,5.0,6.0,7.0,5.0,4.0,Male,31,United Kingdom,NaN
32,62a33ee0bae91e4b8b82eaec,2022-06-10,0:03:30,Data Analyst,Yes,0-40k,Other (Please Specify),Python,8.0,7.0,8.0,7.0,7.0,Male,25,India,NaN
33,62a33ee80f8c8599d5af14b7,2022-06-10,0:01:37,Data Engineer,No,125k-150k,Tech,Other:SQL,8.0,10.0,10.0,9.0,9.0,Male,43,United States,NaN
34,62a33efe0a77c1a77f65bf1e,2022-06-10,0:02:08,Data Analyst,No,41k-65k,Finance,Python,2.0,3.0,5.0,5.0,5.0,Female,26,Canada,NaN
35,62a33f0ef408bae018ed3aeb,2022-06-10,0:03:54,Other (Please Specify):FP&A Analyst,No,41k-65k,Other (Please Specify):Automotive,Python,5.0,10.0,8.0,8.0,7.0,Male,32,Other (Please Specify):Japan,NaN
36,62a33f17f8f7561645852867,2022-06-10,0:02:28,Other (Please Specify):BI Developer,No,0-40k,Tech,Python,2.0,9.0,7.0,7.0,6.0,Male,31,Other (Please Specify):Greece,NaN
37,62a33f52bc6861bf3176c72c,2022-06-10,0:01:33,Data Analyst,Yes,86k-105k,Healthcare,Other:sql,3.0,5.0,6.0,4.0,5.0,Male,29,United States,NaN
38,62a33f56cf255543173005e9,2022-06-10,0:00:56,Data Analyst,Yes,0-40k,Other (Please Specify):Automotive,Python,3.0,1.0,3.0,2.0,1.0,Male,24,Other (Please Specify):Perú,NaN
39,62a33f5a5d257a28a30d7bb5,2022-06-10,0:02:38,Student/Looking/None,Yes,41k-65k,Construction,Python,2.0,0.0,2.0,2.0,0.0,Male,34,United States,NaN
40,62a33fa5cec54911e9ca51f1,2022-06-10,0:01:52,Data Analyst,Yes,41k-65k,Other (Please Specify):Utili,Other:Power bi,5.0,6.0,6.0,5.0,6.0,Male,42,Other (Please Specify):Australia,NaN
41,62a33fcb575fa3a5ae88ad59,2022-06-10,0:02:03,Student/Looking/None,Yes,0-40k,Other (Please Specify):Not working yet,JavaScript,0.0,0.0,0.0,0.0,0.0,Female,40,United States,NaN
42,62a33fcf18134ddc75ce91c3,2022-06-10,0:02:32,Student/Looking/None,No,41k-65k,Telecommunication,Python,3.0,1.0,3.0,4.0,3.0,Male,43,Other (Please Specify):Spain,NaN
43,62a34006d8c00e9f5419d341,2022-06-10,0:02:39,Student/Looking/None,Yes,0-40k,Construction,Python,0.0,0.0,0.0,0.0,0.0,Male,23,Other (Please Specify):Kenya,NaN
44,62a34020575fa3a5ae88ade0,2022-06-10,0:01:11,Student/Looking/None,Yes,0-40k,Education,Python,5.0,5.0,3.0,5.0,6.0,Male,23,Other (Please Specify):Japan,NaN
45,62a34038b4da29969c62eafe,2022-06-10,0:03:55,Data Analyst,Yes,86k-105k,Other (Please Specify):Manufa,Python,8.0,6.0,2.0,3.0,7.0,Male,28,United States,NaN
46,62a3406b575fa3a5ae88ae78,2022-06-10,0:01:25,Data Analyst,No,66k-85k,Finance,Other:SQL,5.0,7.0,1.0,1.0,8.0,Male,32,United States,NaN
47,62a340cab4da29969c62ec01,2022-06-10,0:02:47,Data Analyst,Yes,66k-85k,Other (Please Specify):Manufacturing (Chemicals),R,7.0,8.0,10.0,8.0,9.0,Female,41,United States,NaN
48,62a340d62e54c9003e5324b4,2022-06-10,0:00:56,Data Analyst,Yes,41k-65k,Finance,Python,5.0,6.0,6.0,6.0,6.0,Male,33,United Kingdom,High School
49,62a340e10a77c1a77f65c2e7,2022-06-10,0:01:57,"Other (Please Specify):Manager, Business Intel...",Yes,150k-225k,Tech,Python,10.0,8.0,9.0,8.0,10.0,Male,38,United States,NaN
50,62a340f5bc6861bf3176caa4,2022-06-10,0:02:32,Data Analyst,No,0-40k,Tech,Other:sql,8.0,8.0,8.0,8.0,10.0,Female,22,India,NaN
51,62a34117cec54911e9ca54e7,2022-06-10,0:01:59,Student/Looking/None,Yes,0-40k,Other (Please Specify):Currently studying . Pr...,R,1.0,3.0,6.0,6.0,9.0,Male,36,Other (Please Specify):Barbados,Bachelors
52,62a3413a5d257a28a30d8074,2022-06-10,0:01:18,Data Engineer,No,66k-85k,Finance,Python,2.0,1.0,1.0,1.0,7.0,Female,28,United States,Masters
53,62a341a1f3072dd8926229a5,2022-06-10,0:08:11,Student/Looking/None,Yes,0-40k,Other (Please Specify):Not working at the mome...,Other:If SQL is categorised as a programming l...,NaN,NaN,NaN,NaN,7.0,Male,30,Other (Please Specify):South Africa,NaN
54,62a341b0f8f7561645852d1d,2022-06-10,0:01:44,Data Analyst,Yes,66k-85k,Tech,Python,6.0,6.0,6.0,6.0,6.0,Female,24,United States,Bachelors
55,62a341e8f8d5efcc22f7d002,2022-06-10,0:01:58,Other (Please Specify):Business Analyst,No,41k-65k,Other (Please Specify):Third Party Logistics,C/C++,3.0,6.0,7.0,7.0,3.0,Male,29,United States,Bachelors
56,62a34210cf25554317300c02,2022-06-10,0:02:15,Data Analyst,No,0-40k,Tech,Python,4.0,9.0,10.0,9.0,10.0,Male,29,Other (Please Specify):Colombia,Associates
57,62a3424eb4da29969c62eedd,2022-06-10,0:02:04,Other (Please Specify):Business Analyst,Yes,41k-65k,Other (Please Specify):Automotive,Python,6.0,8.0,8.0,7.0,7.0,Male,38,Other (Please Specify):Germany,Masters
58,62a34256bae91e4b8b82f16d,2022-06-10,0:01:46,Data Analyst,Yes,0-40k,Finance,Other:I don’t know any,3.0,5.0,4.0,3.0,3.0,Male,31,Other (Please Specify):Bulgaria,Masters
59,62a3426cf408bae018ed409b,2022-06-10,0:01:33,Student/Looking/None,No,0-40k,Tech,Python,1.0,4.0,5.0,5.0,1.0,Male,25,United States,Masters
60,62a34272f8d5efcc22f7d15f,2022-06-10,0:01:09,Data Analyst,No,66k-85k,Telecommunication,Python,4.0,6.0,4.0,5.0,4.0,Male,24,United States,Masters
61,62a34340bc6861bf3176d05b,2022-06-10,0:04:03,Other (Please Specify):Business Intelligence C...,Yes,41k-65k,Tech,Python,6.0,7.0,4.0,3.0,8.0,Male,28,Other (Please Specify):Turkey,Bachelors
62,62a34383b4da29969c62f1be,2022-06-10,0:01:03,Student/Looking/None,No,0-40k,Tech,Python,7.0,5.0,8.0,0.0,0.0,Female,23,India,Bachelors
63,62a34389cec54911e9ca5a22,2022-06-10,0:01:01,Data Engineer,No,0-40k,Tech,R,2.0,3.0,2.0,5.0,7.0,Male,21,Other (Please Specify):Spain,Masters
64,62a343a22e54c9003e532a2a,2022-06-10,0:02:43,Data Analyst,No,0-40k,Other (Please Specify):Energy,Python,4.0,4.0,4.0,4.0,6.0,Male,29,Other (Please Specify):France,Bachelors
65,62a343d9f3072dd892622fe4,2022-06-10,0:03:15,Data Analyst,Yes,41k-65k,Tech,Python,5.0,6.0,7.0,7.0,6.0,Male,25,United States,Bachelors
66,62a34400d8c00e9f5419dc2b,2022-06-10,0:01:24,Data Analyst,No,41k-65k,Tech,Python,6.0,6.0,6.0,6.0,5.0,Male,27,Other (Please Specify):Germany,Masters
67,62a34425f8d5efcc22f7d525,2022-06-10,0:01:28,Data Analyst,Yes,41k-65k,Tech,Python,3.0,9.0,10.0,8.0,9.0,Male,23,India,Bachelors
68,62a34449575fa3a5ae88b637,2022-06-10,0:02:36,Other (Please Specify):Sr. Supply Chain Analyst,No,86k-105k,Other (Please Specify):Food & Beverage,R,4.0,3.0,3.0,5.0,5.0,Male,32,United States,Masters
69,62a3445dcf255543173011e1,2022-06-10,0:02:41,Student/Looking/None,Yes,106k-125k,Healthcare,Python,5.0,5.0,7.0,5.0,7.0,Male,22,India,Bachelors
70,62a3447a575fa3a5ae88b6c0,2022-06-10,0:04:14,Data Analyst,No,0-40k,Tech,Python,2.0,9.0,9.0,8.0,2.0,Male,25,Other (Please Specify):Thailand,Bachelors
71,62a3449f7dc029e2d66bf5d1,2022-06-10,0:01:15,Data Analyst,Yes,0-40k,Telecommunication,Python,2.0,8.0,6.0,6.0,5.0,Female,36,Other (Please Specify):Germany,Masters
72,62a344c5f408bae018ed4806,2022-06-10,0:02:21,Data Analyst,Yes,106k-125k,Tech,Other:SQL,10.0,6.0,9.0,5.0,7.0,Female,27,United States,Bachelors
73,62a344c6f8d5efcc22f7d6e1,2022-06-10,0:02:17,Other (Please Specify):Business analyst,Yes,0-40k,Tech,Python,5.0,5.0,5.0,5.0,1.0,Male,23,India,Bachelors
74,62a344e1f3072dd892623328,2022-06-10,0:01:32,Student/Looking/None,Yes,0-40k,Tech,Other:Sql,2.0,3.0,3.0,3.0,6.0,Male,26,Other (Please Specify):Netherlands,Bachelors
75,62a3450424a262602738357f,2022-06-10,0:01:19,Other (Please Specify):Director of Data Analytics,No,86k-105k,Healthcare,Python,9.0,10.0,10.0,10.0,10.0,Female,33,United States,PhD
76,62a3452818134ddc75ce9e1b,2022-06-10,0:01:33,Data Analyst,Yes,106k-125k,Other (Please Specify):Automotive,Python,3.0,5.0,3.0,3.0,5.0,Male,27,Other (Please Specify):Turkey,Masters
77,62a345490a77c1a77f65cc5b,2022-06-10,0:01:38,Data Analyst,Yes,41k-65k,Education,R,3.0,6.0,5.0,4.0,4.0,Male,42,United States,Associates
78,62a3455bbc6861bf3176d57a,2022-06-10,0:02:36,Data Analyst,Yes,0-40k,Tech,Python,6.0,7.0,8.0,7.0,8.0,Male,29,Other (Please Specify):Spain,Masters
79,62a3457bf8d5efcc22f7da17,2022-06-10,0:01:08,Data Analyst,No,125k-150k,Tech,Python,4.0,7.0,6.0,4.0,4.0,Female,27,United States,Masters
80,62a345b2bae91e4b8b82fad6,2022-06-10,0:01:41,Student/Looking/None,No,41k-65k,Healthcare,Python,0.0,10.0,10.0,10.0,2.0,Female,39,United States,Bachelors
81,62a345c47dc029e2d66bf80a,2022-06-10,0:01:36,Data Analyst,Yes,41k-65k,Telecommunication,Python,6.0,6.0,7.0,5.0,7.0,Male,31,Other (Please Specify):Denmark,Masters
82,62a345e25d257a28a30d8b43,2022-06-10,0:03:09,Data Analyst,Yes,66k-85k,Other (Please Specify):Marketing,Python,7.0,7.0,5.0,9.0,8.0,Male,29,Other (Please Specify):Brazil,Bachelors
83,62a34646f8d5efcc22f7dc5c,2022-06-10,0:01:22,Data Analyst,Yes,66k-85k,Education,R,7.0,7.0,7.0,7.0,7.0,Male,31,United States,Masters
84,62a34687f408bae018ed4c52,2022-06-10,0:01:30,Data Analyst,Yes,0-40k,Finance,Python,10.0,9.0,9.0,10.0,10.0,Male,30,Other (Please Specify):Mexico,Masters
85,62a346a37dc029e2d66bfa6d,2022-06-10,0:03:05,Data Engineer,Yes,0-40k,Tech,Python,7.0,8.0,6.0,5.0,9.0,Male,33,Other (Please Specify):Mexico,Masters
86,62a346a95d257a28a30d8cb9,2022-06-10,0:00:58,Data Analyst,No,66k-85k,Other (Please Specify):Retail,Python,7.0,8.0,9.0,7.0,7.0,Male,25,United States,Bachelors
87,62a346b4bc6861bf3176d7ce,2022-06-10,0:01:09,Student/Looking/None,No,0-40k,Tech,R,0.0,0.0,0.0,0.0,0.0,Male,23,India,Bachelors
88,62a346cef8f756164585385b,2022-06-10,0:01:51,Data Analyst,Yes,41k-65k,Other (Please Specify):Advertising,Other:Dont require,4.0,4.0,3.0,3.0,6.0,Male,33,United States,Bachelors
89,62a346d724a2626027383abd,2022-06-10,0:02:29,Other (Please Specify):Business Analyst,Yes,66k-85k,Other (Please Specify):Logistics,Python,7.0,9.0,9.0,8.0,9.0,Male,35,Other (Please Specify):Chile,Bachelors
90,62a346d90a77c1a77f65d08d,2022-06-10,0:02:39,Data Analyst,No,41k-65k,Other (Please Specify):Staffing and Recruting,Python,6.0,8.0,5.0,NaN,9.0,Female,42,Other (Please Specify):Greece,Masters
91,62a34726f8d5efcc22f7dec7,2022-06-10,0:01:14,Data Analyst,No,66k-85k,Tech,Python,3.0,4.0,2.0,1.0,4.0,Male,25,United States,Bachelors
92,62a3476c5d257a28a30d8e6d,2022-06-10,0:03:00,Data Analyst,No,86k-105k,Other (Please Specify):Automotive,Python,5.0,4.0,5.0,4.0,6.0,Male,23,United States,Bachelors
93,62a347b4f8f7561645853a98,2022-06-10,0:02:02,Other (Please Specify):Learning Management Spe...,No,41k-65k,Healthcare,JavaScript,2.0,4.0,6.0,5.0,4.0,Female,51,United States,Bachelors
94,62a347f6b4da29969c62fb79,2022-06-10,0:01:45,Data Analyst,No,0-40k,Telecommunication,Other,1.0,4.0,4.0,3.0,6.0,Male,30,United Kingdom,Bachelors
95,62a3483018134ddc75cea4e6,2022-06-10,0:01:41,Data Analyst,Yes,41k-65k,Finance,Python,8.0,9.0,9.0,9.0,8.0,Male,23,India,Bachelors
96,62a348650f8c8599d5af2b77,2022-06-10,0:01:06,Other (Please Specify):Research Analyst,Yes,41k-65k,Other (Please Specify):Advertising,R,3.0,5.0,5.0,6.0,4.0,Male,24,Canada,Bachelors
97,62a3489318134ddc75cea659,2022-06-10,0:01:06,Student/Looking/None,Yes,41k-65k,Tech,Python,6.0,6.0,6.0,6.0,6.0,Male,25,Other (Please Specify):Australia,Masters
98,62a348bf2e54c9003e533634,2022-06-10,0:02:22,Data Analyst,Yes,41k-65k,Finance,Python,4.0,4.0,6.0,4.0,6.0,Female,55,United States,Masters
99,62a348c2f3072dd892623c10,2022-06-10,0:01:56,Data Analyst,No,86k-105k,Other (Please Specify):Biotech,R,8.0,10.0,8.0,7.0,10.0,Female,30,United States,Masters
100,62a348f2f8d5efcc22f7e2ba,2022-06-10,0:01:10,Data Analyst,Yes,41k-65k,Other (Please Specify):Consulting,Python,9.0,9.0,9.0,9.0,4.0,Male,25,Canada,Bachelors
101,62a349160a77c1a77f65d4db,2022-06-10,0:00:28,Data Analyst,Yes,66k-85k,Other (Please Specify):Consumer Elec,Python,6.0,9.0,7.0,6.0,7.0,Male,28,United States,Masters
102,62a3493fb4da29969c62fe63,2022-06-10,0:02:22,Other (Please Specify):Insights analyst,Yes,41k-65k,Other (Please Specify):Consulting,Python,8.0,8.0,9.0,9.0,10.0,Male,34,United Kingdom,Bachelors
103,62a3496e575fa3a5ae88c4e6,2022-06-10,0:03:18,Data Analyst,Yes,0-40k,Tech,Python,8.0,10.0,9.0,9.0,8.0,Female,28,Other (Please Specify):Costa Rica,Bachelors
104,62a3498e575fa3a5ae88c554,2022-06-10,0:01:55,Student/Looking/None,No,0-40k,Other (Please Specify):Semiconductor manufactu...,Other,7.0,9.0,7.0,8.0,10.0,Male,24,Other (Please Specify):Vietnam,Bachelors
105,62a34991b4da29969c62ff4b,2022-06-10,0:01:15,Student/Looking/None,Yes,0-40k,Healthcare,Python,3.0,7.0,7.0,7.0,2.0,Male,31,United States,Masters
106,62a349bbf8f756164585400d,2022-06-10,0:02:07,Data Analyst,Yes,41k-65k,Other (Please Specify):Supply Chain - warehous...,Other:Knowledge of Excel and SQL yet,3.0,6.0,6.0,6.0,4.0,Male,25,Canada,Bachelors
107,62a349c7cec54911e9ca67c7,2022-06-10,0:01:05,Data Analyst,Yes,106k-125k,Finance,Python,5.0,1.0,4.0,3.0,4.0,Female,38,United States,Bachelors
108,62a349d5d8c00e9f5419ead2,2022-06-10,0:01:32,Data Analyst,No,41k-65k,Finance,Python,5.0,5.0,5.0,5.0,5.0,Male,30,Other (Please Specify):Netherlands,Bachelors
109,62a349e6b4da29969c63000c,2022-06-10,0:01:32,Data Analyst,Yes,0-40k,Tech,C/C++,0.0,0.0,0.0,2.0,5.0,Male,25,India,Bachelors
110,62a34a03cec54911e9ca6869,2022-06-10,0:01:08,Data Analyst,Yes,0-40k,Tech,Python,1.0,2.0,1.0,5.0,6.0,Female,29,Other (Please Specify):Nigeria,Bachelors
111,62a34ab15d257a28a30d9589,2022-06-10,0:04:27,Data Scientist,Yes,150k-225k,Finance,Python,7.0,5.0,3.0,6.0,4.0,Male,21,Other (Please Specify):Portugal,Masters
112,62a34abc0f8c8599d5af31c5,2022-06-10,0:02:00,Data Analyst,Yes,66k-85k,Other (Please Specify):Distribution,Other:SQL,5.0,8.0,8.0,7.0,7.0,Female,39,United States,Bachelors
113,62a34b07cec54911e9ca6b6e,2022-06-10,0:01:19,Student/Looking/None,No,0-40k,Other (Please Specify),Python,0.0,0.0,0.0,0.0,5.0,Male,25,Other (Please Specify):turkey,Bachelors
114,62a34b0eb4da29969c6302ce,2022-06-10,0:02:36,Other (Please Specify):Does a social media ana...,Yes,86k-105k,Finance,Other:I don't use programming in my role,7.0,9.0,10.0,6.0,4.0,Female,42,United States,Masters
115,62a34b1b0f8c8599d5af328b,2022-06-10,0:00:48,Data Analyst,No,41k-65k,Tech,R,10.0,8.0,9.0,10.0,10.0,Male,25,United States,Bachelors
116,62a34b5b5d257a28a30d96a6,2022-06-10,0:01:20,Data Scientist,No,86k-105k,Finance,Python,8.0,7.0,6.0,6.0,9.0,Male,22,United States,Bachelors
117,62a34b7ebae91e4b8b83076c,2022-06-10,0:02:04,Data Analyst,No,0-40k,Other (Please Specify):Customer Service,Python,1.0,4.0,4.0,3.0,5.0,Male,23,Other (Please Specify):Colombia,High School
118,62a34b99cec54911e9ca6e14,2022-06-10,0:02:36,Data Engineer,Yes,41k-65k,Other (Please Specify):Ecom,JavaScript,6.0,6.0,6.0,6.0,6.0,Male,25,Other (Please Specify):Egypt,High School
119,62a34bb0f3072dd892624210,2022-06-10,0:01:05,Data Engineer,Yes,66k-85k,Other (Please Specify):Consulti,Python,5.0,7.0,7.0,6.0,7.0,Male,45,Canada,Masters
120,62a34bd0cf2555431730208b,2022-06-10,0:01:29,Data Analyst,Yes,66k-85k,Healthcare,Other:Excel/SQL,7.0,3.0,8.0,6.0,8.0,Male,24,United States,Bachelors
121,62a34bd4f408bae018ed57bd,2022-06-10,0:03:57,Student/Looking/None,No,0-40k,Other (Please Specify):State Government,R,1.0,9.0,6.0,0.0,0.0,Male,25,United States,NaN
122,62a34c66b4da29969c6305af,2022-06-10,0:01:36,Data Analyst,Yes,66k-85k,Other (Please Specify):Marketing,Python,9.0,8.0,9.0,9.0,8.0,Male,26,United States,Bachelors
123,62a34d1ff8f756164585465c,2022-06-10,0:01:41,Data Analyst,No,41k-65k,Tech,R,4.0,7.0,8.0,8.0,7.0,Male,23,Canada,Bachelors

In [14]:
# drop duplicates in case of any

df.drop_duplicates()

,Unique ID,Date Taken (America/New_York),Time Spent,Job Title,Career Switch to Data,Annual Salary (USD),Working Industry,Favorite Programming Language,Happy with salary,Happy with work-life balance,Happy with coworkers,Happy with management,Happy with learning opportunities,Gender,Age,Country,Level of Education
0,62a33b3db4da29969c62df3d,2022-06-10,0:00:44,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,9.0,7.0,5.0,7.0,Male,26,United States,NaN
1,62a33ba1bae91e4b8b82e35c,2022-06-10,0:01:30,Data Analyst,No,41k-65k,Finance,R,1.0,2.0,5.0,2.0,3.0,Male,36,Canada,NaN
2,62a33c2cbc6861bf3176bec1,2022-06-10,0:02:18,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,0.0,8.0,7.0,5.0,7.0,Male,23,Other (Please Specify):Nigeria,NaN
3,62a33c8624a26260273822f9,2022-06-10,0:02:10,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,10.0,6.0,7.0,10.0,10.0,Female,35,Canada,NaN
4,62a33c91f3072dd892621e03,2022-06-10,0:01:51,Data Analyst,Yes,41k-65k,Healthcare,R,1.0,4.0,4.0,4.0,1.0,Male,44,United States,NaN
5,62a33cb6cf25554317300177,2022-06-10,0:02:34,Data Analyst,Yes,0-40k,Other (Please Specify):Coworking space,Python,2.0,3.0,3.0,3.0,2.0,Male,33,Other (Please Specify):Republic democratic of ...,NaN
6,62a33cb72e54c9003e531c65,2022-06-10,0:01:15,Data Scientist,Yes,0-40k,Finance,Python,0.0,6.0,6.0,6.0,5.0,Male,24,Other (Please Specify),NaN
7,62a33cd30f8c8599d5af0f8f,2022-06-10,0:01:25,Data Engineer,Yes,125k-150k,Other (Please Specify):Retail,Other:SQL,10.0,5.0,5.0,5.0,9.0,Male,35,United States,NaN
8,62a33cd3cf255543173001d9,2022-06-10,0:02:10,Data Analyst,Yes,86k-105k,Healthcare,R,4.0,4.0,4.0,4.0,5.0,Male,35,United States,NaN
9,62a33cd8bc6861bf3176c05f,2022-06-10,0:01:27,Data Analyst,Yes,41k-65k,Telecommunication,Python,2.0,0.0,3.0,3.0,4.0,Male,28,United States,NaN
10,62a33ce918134ddc75ce8c30,2022-06-10,0:01:29,Data Analyst,Yes,66k-85k,Other (Please Specify):Logistics,Python,10.0,10.0,8.0,8.0,10.0,Male,37,Canada,NaN
11,62a33cf30a77c1a77f65baa2,2022-06-10,0:02:31,Data Analyst,Yes,0-40k,Other (Please Specify):Igaming,Python,3.0,8.0,10.0,10.0,8.0,Male,32,Other (Please Specify):Serbia,NaN
12,62a33d15f408bae018ed370d,2022-06-10,0:03:20,Data Analyst,Yes,0-40k,Tech,R,1.0,10.0,9.0,9.0,10.0,Male,34,Other (Please Specify):Argentina,NaN
13,62a33d1ebae91e4b8b82e707,2022-06-10,0:00:55,Data Scientist,Yes,0-40k,Education,Python,3.0,10.0,10.0,6.0,8.0,Male,30,United Kingdom,NaN
14,62a33d4624a26260273824c4,2022-06-10,0:01:24,Data Analyst,No,41k-65k,Construction,R,4.0,5.0,5.0,5.0,5.0,Male,31,United States,NaN
15,62a33d5c0f8c8599d5af107c,2022-06-10,0:00:47,Data Analyst,Yes,41k-65k,Finance,Python,4.0,10.0,7.0,7.0,5.0,Male,29,United States,NaN
16,62a33d850f8c8599d5af10cb,2022-06-10,0:01:06,Data Analyst,Yes,0-40k,Tech,Python,1.0,2.0,4.0,2.0,2.0,Male,22,Other (Please Specify):Niger,NaN
17,62a33d9bf8f7561645852496,2022-06-10,0:01:04,Student/Looking/None,Yes,0-40k,Other (Please Specify):Retail,Python,1.0,3.0,2.0,2.0,1.0,Male,23,United States,NaN
18,62a33dbdd8c00e9f5419cd65,2022-06-10,0:01:05,Student/Looking/None,No,41k-65k,Tech,R,7.0,8.0,8.0,6.0,3.0,Female,26,Canada,NaN
19,62a33de124a26260273826b2,2022-06-10,0:01:21,Data Analyst,No,0-40k,Other (Please Specify):Aviation,Python,1.0,1.0,1.0,1.0,0.0,Male,28,Other (Please Specify):Nigeria,NaN
20,62a33dedd8c00e9f5419ce2b,2022-06-10,0:01:23,Data Analyst,Yes,41k-65k,Finance,Python,5.0,5.0,5.0,5.0,5.0,Male,29,Other (Please Specify):Kenya,NaN
21,62a33dfbd8c00e9f5419ceda,2022-06-10,0:01:35,Data Analyst,Yes,106k-125k,Tech,Other:Mostly use sql but that’s not programmin...,10.0,5.0,10.0,6.0,10.0,Female,31,United States,NaN
22,62a33e38f3072dd8926221d3,2022-06-10,0:01:25,Data Analyst,Yes,0-40k,Healthcare,Python,5.0,6.0,8.0,8.0,1.0,Male,28,Other (Please Specify):Azerbaijan,NaN
23,62a33e54d8c00e9f5419cfe9,2022-06-10,0:01:47,Data Analyst,No,0-40k,Finance,Python,4.0,4.0,4.0,4.0,4.0,Male,32,Other (Please Specify):Argentina,NaN
24,62a33e62575fa3a5ae88aabf,2022-06-10,0:02:14,Data Analyst,No,0-40k,Tech,Python,7.0,8.0,8.0,8.0,8.0,Male,24,Other (Please Specify):Sudan,NaN
25,62a33e63cec54911e9ca4f99,2022-06-10,0:02:21,Data Analyst,No,0-40k,Tech,Python,4.0,6.0,6.0,6.0,7.0,Male,31,India,NaN
26,62a33e72bae91e4b8b82ea1a,2022-06-10,0:02:07,Data Analyst,No,66k-85k,Other (Please Specify):Insurance,Other:SQL,7.0,10.0,5.0,5.0,2.0,Male,23,United States,NaN
27,62a33e890f8c8599d5af13b9,2022-06-10,0:01:20,Data Analyst,Yes,106k-125k,Other (Please Specify):Energy,Python,1.0,6.0,9.0,1.0,2.0,Female,33,United States,NaN
28,62a33e8bf8d5efcc22f7c79a,2022-06-10,0:01:34,Data Analyst,No,86k-105k,Healthcare,Other:Qlik sense script,6.0,7.0,7.0,7.0,4.0,Male,43,United States,NaN
29,62a33e90cec54911e9ca5031,2022-06-10,0:01:34,Student/Looking/None,Yes,0-40k,Other (Please Specify):Oil and gas,R,0.0,0.0,5.0,0.0,0.0,Female,23,Other (Please Specify):Nigeria,NaN
30,62a33e9df8f756164585277b,2022-06-10,0:01:47,Student/Looking/None,Yes,41k-65k,Finance,Python,10.0,7.0,10.0,10.0,3.0,Male,31,United States,NaN
31,62a33eb6bc6861bf3176c5a3,2022-06-10,0:01:38,Data Analyst,Yes,66k-85k,Finance,Python,5.0,6.0,7.0,5.0,4.0,Male,31,United Kingdom,NaN
32,62a33ee0bae91e4b8b82eaec,2022-06-10,0:03:30,Data Analyst,Yes,0-40k,Other (Please Specify),Python,8.0,7.0,8.0,7.0,7.0,Male,25,India,NaN
33,62a33ee80f8c8599d5af14b7,2022-06-10,0:01:37,Data Engineer,No,125k-150k,Tech,Other:SQL,8.0,10.0,10.0,9.0,9.0,Male,43,United States,NaN
34,62a33efe0a77c1a77f65bf1e,2022-06-10,0:02:08,Data Analyst,No,41k-65k,Finance,Python,2.0,3.0,5.0,5.0,5.0,Female,26,Canada,NaN
35,62a33f0ef408bae018ed3aeb,2022-06-10,0:03:54,Other (Please Specify):FP&A Analyst,No,41k-65k,Other (Please Specify):Automotive,Python,5.0,10.0,8.0,8.0,7.0,Male,32,Other (Please Specify):Japan,NaN
36,62a33f17f8f7561645852867,2022-06-10,0:02:28,Other (Please Specify):BI Developer,No,0-40k,Tech,Python,2.0,9.0,7.0,7.0,6.0,Male,31,Other (Please Specify):Greece,NaN
37,62a33f52bc6861bf3176c72c,2022-06-10,0:01:33,Data Analyst,Yes,86k-105k,Healthcare,Other:sql,3.0,5.0,6.0,4.0,5.0,Male,29,United States,NaN
38,62a33f56cf255543173005e9,2022-06-10,0:00:56,Data Analyst,Yes,0-40k,Other (Please Specify):Automotive,Python,3.0,1.0,3.0,2.0,1.0,Male,24,Other (Please Specify):Perú,NaN
39,62a33f5a5d257a28a30d7bb5,2022-06-10,0:02:38,Student/Looking/None,Yes,41k-65k,Construction,Python,2.0,0.0,2.0,2.0,0.0,Male,34,United States,NaN
40,62a33fa5cec54911e9ca51f1,2022-06-10,0:01:52,Data Analyst,Yes,41k-65k,Other (Please Specify):Utili,Other:Power bi,5.0,6.0,6.0,5.0,6.0,Male,42,Other (Please Specify):Australia,NaN
41,62a33fcb575fa3a5ae88ad59,2022-06-10,0:02:03,Student/Looking/None,Yes,0-40k,Other (Please Specify):Not working yet,JavaScript,0.0,0.0,0.0,0.0,0.0,Female,40,United States,NaN
42,62a33fcf18134ddc75ce91c3,2022-06-10,0:02:32,Student/Looking/None,No,41k-65k,Telecommunication,Python,3.0,1.0,3.0,4.0,3.0,Male,43,Other (Please Specify):Spain,NaN
43,62a34006d8c00e9f5419d341,2022-06-10,0:02:39,Student/Looking/None,Yes,0-40k,Construction,Python,0.0,0.0,0.0,0.0,0.0,Male,23,Other (Please Specify):Kenya,NaN
44,62a34020575fa3a5ae88ade0,2022-06-10,0:01:11,Student/Looking/None,Yes,0-40k,Education,Python,5.0,5.0,3.0,5.0,6.0,Male,23,Other (Please Specify):Japan,NaN
45,62a34038b4da29969c62eafe,2022-06-10,0:03:55,Data Analyst,Yes,86k-105k,Other (Please Specify):Manufa,Python,8.0,6.0,2.0,3.0,7.0,Male,28,United States,NaN
46,62a3406b575fa3a5ae88ae78,2022-06-10,0:01:25,Data Analyst,No,66k-85k,Finance,Other:SQL,5.0,7.0,1.0,1.0,8.0,Male,32,United States,NaN
47,62a340cab4da29969c62ec01,2022-06-10,0:02:47,Data Analyst,Yes,66k-85k,Other (Please Specify):Manufacturing (Chemicals),R,7.0,8.0,10.0,8.0,9.0,Female,41,United States,NaN
48,62a340d62e54c9003e5324b4,2022-06-10,0:00:56,Data Analyst,Yes,41k-65k,Finance,Python,5.0,6.0,6.0,6.0,6.0,Male,33,United Kingdom,High School
49,62a340e10a77c1a77f65c2e7,2022-06-10,0:01:57,"Other (Please Specify):Manager, Business Intel...",Yes,150k-225k,Tech,Python,10.0,8.0,9.0,8.0,10.0,Male,38,United States,NaN
50,62a340f5bc6861bf3176caa4,2022-06-10,0:02:32,Data Analyst,No,0-40k,Tech,Other:sql,8.0,8.0,8.0,8.0,10.0,Female,22,India,NaN
51,62a34117cec54911e9ca54e7,2022-06-10,0:01:59,Student/Looking/None,Yes,0-40k,Other (Please Specify):Currently studying . Pr...,R,1.0,3.0,6.0,6.0,9.0,Male,36,Other (Please Specify):Barbados,Bachelors
52,62a3413a5d257a28a30d8074,2022-06-10,0:01:18,Data Engineer,No,66k-85k,Finance,Python,2.0,1.0,1.0,1.0,7.0,Female,28,United States,Masters
53,62a341a1f3072dd8926229a5,2022-06-10,0:08:11,Student/Looking/None,Yes,0-40k,Other (Please Specify):Not working at the mome...,Other:If SQL is categorised as a programming l...,NaN,NaN,NaN,NaN,7.0,Male,30,Other (Please Specify):South Africa,NaN
54,62a341b0f8f7561645852d1d,2022-06-10,0:01:44,Data Analyst,Yes,66k-85k,Tech,Python,6.0,6.0,6.0,6.0,6.0,Female,24,United States,Bachelors
55,62a341e8f8d5efcc22f7d002,2022-06-10,0:01:58,Other (Please Specify):Business Analyst,No,41k-65k,Other (Please Specify):Third Party Logistics,C/C++,3.0,6.0,7.0,7.0,3.0,Male,29,United States,Bachelors
56,62a34210cf25554317300c02,2022-06-10,0:02:15,Data Analyst,No,0-40k,Tech,Python,4.0,9.0,10.0,9.0,10.0,Male,29,Other (Please Specify):Colombia,Associates
57,62a3424eb4da29969c62eedd,2022-06-10,0:02:04,Other (Please Specify):Business Analyst,Yes,41k-65k,Other (Please Specify):Automotive,Python,6.0,8.0,8.0,7.0,7.0,Male,38,Other (Please Specify):Germany,Masters
58,62a34256bae91e4b8b82f16d,2022-06-10,0:01:46,Data Analyst,Yes,0-40k,Finance,Other:I don’t know any,3.0,5.0,4.0,3.0,3.0,Male,31,Other (Please Specify):Bulgaria,Masters
59,62a3426cf408bae018ed409b,2022-06-10,0:01:33,Student/Looking/None,No,0-40k,Tech,Python,1.0,4.0,5.0,5.0,1.0,Male,25,United States,Masters
60,62a34272f8d5efcc22f7d15f,2022-06-10,0:01:09,Data Analyst,No,66k-85k,Telecommunication,Python,4.0,6.0,4.0,5.0,4.0,Male,24,United States,Masters
61,62a34340bc6861bf3176d05b,2022-06-10,0:04:03,Other (Please Specify):Business Intelligence C...,Yes,41k-65k,Tech,Python,6.0,7.0,4.0,3.0,8.0,Male,28,Other (Please Specify):Turkey,Bachelors
62,62a34383b4da29969c62f1be,2022-06-10,0:01:03,Student/Looking/None,No,0-40k,Tech,Python,7.0,5.0,8.0,0.0,0.0,Female,23,India,Bachelors
63,62a34389cec54911e9ca5a22,2022-06-10,0:01:01,Data Engineer,No,0-40k,Tech,R,2.0,3.0,2.0,5.0,7.0,Male,21,Other (Please Specify):Spain,Masters
64,62a343a22e54c9003e532a2a,2022-06-10,0:02:43,Data Analyst,No,0-40k,Other (Please Specify):Energy,Python,4.0,4.0,4.0,4.0,6.0,Male,29,Other (Please Specify):France,Bachelors
65,62a343d9f3072dd892622fe4,2022-06-10,0:03:15,Data Analyst,Yes,41k-65k,Tech,Python,5.0,6.0,7.0,7.0,6.0,Male,25,United States,Bachelors
66,62a34400d8c00e9f5419dc2b,2022-06-10,0:01:24,Data Analyst,No,41k-65k,Tech,Python,6.0,6.0,6.0,6.0,5.0,Male,27,Other (Please Specify):Germany,Masters
67,62a34425f8d5efcc22f7d525,2022-06-10,0:01:28,Data Analyst,Yes,41k-65k,Tech,Python,3.0,9.0,10.0,8.0,9.0,Male,23,India,Bachelors
68,62a34449575fa3a5ae88b637,2022-06-10,0:02:36,Other (Please Specify):Sr. Supply Chain Analyst,No,86k-105k,Other (Please Specify):Food & Beverage,R,4.0,3.0,3.0,5.0,5.0,Male,32,United States,Masters
69,62a3445dcf255543173011e1,2022-06-10,0:02:41,Student/Looking/None,Yes,106k-125k,Healthcare,Python,5.0,5.0,7.0,5.0,7.0,Male,22,India,Bachelors
70,62a3447a575fa3a5ae88b6c0,2022-06-10,0:04:14,Data Analyst,No,0-40k,Tech,Python,2.0,9.0,9.0,8.0,2.0,Male,25,Other (Please Specify):Thailand,Bachelors
71,62a3449f7dc029e2d66bf5d1,2022-06-10,0:01:15,Data Analyst,Yes,0-40k,Telecommunication,Python,2.0,8.0,6.0,6.0,5.0,Female,36,Other (Please Specify):Germany,Masters
72,62a344c5f408bae018ed4806,2022-06-10,0:02:21,Data Analyst,Yes,106k-125k,Tech,Other:SQL,10.0,6.0,9.0,5.0,7.0,Female,27,United States,Bachelors
73,62a344c6f8d5efcc22f7d6e1,2022-06-10,0:02:17,Other (Please Specify):Business analyst,Yes,0-40k,Tech,Python,5.0,5.0,5.0,5.0,1.0,Male,23,India,Bachelors
74,62a344e1f3072dd892623328,2022-06-10,0:01:32,Student/Looking/None,Yes,0-40k,Tech,Other:Sql,2.0,3.0,3.0,3.0,6.0,Male,26,Other (Please Specify):Netherlands,Bachelors
75,62a3450424a262602738357f,2022-06-10,0:01:19,Other (Please Specify):Director of Data Analytics,No,86k-105k,Healthcare,Python,9.0,10.0,10.0,10.0,10.0,Female,33,United States,PhD
76,62a3452818134ddc75ce9e1b,2022-06-10,0:01:33,Data Analyst,Yes,106k-125k,Other (Please Specify):Automotive,Python,3.0,5.0,3.0,3.0,5.0,Male,27,Other (Please Specify):Turkey,Masters
77,62a345490a77c1a77f65cc5b,2022-06-10,0:01:38,Data Analyst,Yes,41k-65k,Education,R,3.0,6.0,5.0,4.0,4.0,Male,42,United States,Associates
78,62a3455bbc6861bf3176d57a,2022-06-10,0:02:36,Data Analyst,Yes,0-40k,Tech,Python,6.0,7.0,8.0,7.0,8.0,Male,29,Other (Please Specify):Spain,Masters
79,62a3457bf8d5efcc22f7da17,2022-06-10,0:01:08,Data Analyst,No,125k-150k,Tech,Python,4.0,7.0,6.0,4.0,4.0,Female,27,United States,Masters
80,62a345b2bae91e4b8b82fad6,2022-06-10,0:01:41,Student/Looking/None,No,41k-65k,Healthcare,Python,0.0,10.0,10.0,10.0,2.0,Female,39,United States,Bachelors
81,62a345c47dc029e2d66bf80a,2022-06-10,0:01:36,Data Analyst,Yes,41k-65k,Telecommunication,Python,6.0,6.0,7.0,5.0,7.0,Male,31,Other (Please Specify):Denmark,Masters
82,62a345e25d257a28a30d8b43,2022-06-10,0:03:09,Data Analyst,Yes,66k-85k,Other (Please Specify):Marketing,Python,7.0,7.0,5.0,9.0,8.0,Male,29,Other (Please Specify):Brazil,Bachelors
83,62a34646f8d5efcc22f7dc5c,2022-06-10,0:01:22,Data Analyst,Yes,66k-85k,Education,R,7.0,7.0,7.0,7.0,7.0,Male,31,United States,Masters
84,62a34687f408bae018ed4c52,2022-06-10,0:01:30,Data Analyst,Yes,0-40k,Finance,Python,10.0,9.0,9.0,10.0,10.0,Male,30,Other (Please Specify):Mexico,Masters
85,62a346a37dc029e2d66bfa6d,2022-06-10,0:03:05,Data Engineer,Yes,0-40k,Tech,Python,7.0,8.0,6.0,5.0,9.0,Male,33,Other (Please Specify):Mexico,Masters
86,62a346a95d257a28a30d8cb9,2022-06-10,0:00:58,Data Analyst,No,66k-85k,Other (Please Specify):Retail,Python,7.0,8.0,9.0,7.0,7.0,Male,25,United States,Bachelors
87,62a346b4bc6861bf3176d7ce,2022-06-10,0:01:09,Student/Looking/None,No,0-40k,Tech,R,0.0,0.0,0.0,0.0,0.0,Male,23,India,Bachelors
88,62a346cef8f756164585385b,2022-06-10,0:01:51,Data Analyst,Yes,41k-65k,Other (Please Specify):Advertising,Other:Dont require,4.0,4.0,3.0,3.0,6.0,Male,33,United States,Bachelors
89,62a346d724a2626027383abd,2022-06-10,0:02:29,Other (Please Specify):Business Analyst,Yes,66k-85k,Other (Please Specify):Logistics,Python,7.0,9.0,9.0,8.0,9.0,Male,35,Other (Please Specify):Chile,Bachelors
90,62a346d90a77c1a77f65d08d,2022-06-10,0:02:39,Data Analyst,No,41k-65k,Other (Please Specify):Staffing and Recruting,Python,6.0,8.0,5.0,NaN,9.0,Female,42,Other (Please Specify):Greece,Masters
91,62a34726f8d5efcc22f7dec7,2022-06-10,0:01:14,Data Analyst,No,66k-85k,Tech,Python,3.0,4.0,2.0,1.0,4.0,Male,25,United States,Bachelors
92,62a3476c5d257a28a30d8e6d,2022-06-10,0:03:00,Data Analyst,No,86k-105k,Other (Please Specify):Automotive,Python,5.0,4.0,5.0,4.0,6.0,Male,23,United States,Bachelors
93,62a347b4f8f7561645853a98,2022-06-10,0:02:02,Other (Please Specify):Learning Management Spe...,No,41k-65k,Healthcare,JavaScript,2.0,4.0,6.0,5.0,4.0,Female,51,United States,Bachelors
94,62a347f6b4da29969c62fb79,2022-06-10,0:01:45,Data Analyst,No,0-40k,Telecommunication,Other,1.0,4.0,4.0,3.0,6.0,Male,30,United Kingdom,Bachelors
95,62a3483018134ddc75cea4e6,2022-06-10,0:01:41,Data Analyst,Yes,41k-65k,Finance,Python,8.0,9.0,9.0,9.0,8.0,Male,23,India,Bachelors
96,62a348650f8c8599d5af2b77,2022-06-10,0:01:06,Other (Please Specify):Research Analyst,Yes,41k-65k,Other (Please Specify):Advertising,R,3.0,5.0,5.0,6.0,4.0,Male,24,Canada,Bachelors
97,62a3489318134ddc75cea659,2022-06-10,0:01:06,Student/Looking/None,Yes,41k-65k,Tech,Python,6.0,6.0,6.0,6.0,6.0,Male,25,Other (Please Specify):Australia,Masters
98,62a348bf2e54c9003e533634,2022-06-10,0:02:22,Data Analyst,Yes,41k-65k,Finance,Python,4.0,4.0,6.0,4.0,6.0,Female,55,United States,Masters
99,62a348c2f3072dd892623c10,2022-06-10,0:01:56,Data Analyst,No,86k-105k,Other (Please Specify):Biotech,R,8.0,10.0,8.0,7.0,10.0,Female,30,United States,Masters
100,62a348f2f8d5efcc22f7e2ba,2022-06-10,0:01:10,Data Analyst,Yes,41k-65k,Other (Please Specify):Consulting,Python,9.0,9.0,9.0,9.0,4.0,Male,25,Canada,Bachelors
101,62a349160a77c1a77f65d4db,2022-06-10,0:00:28,Data Analyst,Yes,66k-85k,Other (Please Specify):Consumer Elec,Python,6.0,9.0,7.0,6.0,7.0,Male,28,United States,Masters
102,62a3493fb4da29969c62fe63,2022-06-10,0:02:22,Other (Please Specify):Insights analyst,Yes,41k-65k,Other (Please Specify):Consulting,Python,8.0,8.0,9.0,9.0,10.0,Male,34,United Kingdom,Bachelors
103,62a3496e575fa3a5ae88c4e6,2022-06-10,0:03:18,Data Analyst,Yes,0-40k,Tech,Python,8.0,10.0,9.0,9.0,8.0,Female,28,Other (Please Specify):Costa Rica,Bachelors
104,62a3498e575fa3a5ae88c554,2022-06-10,0:01:55,Student/Looking/None,No,0-40k,Other (Please Specify):Semiconductor manufactu...,Other,7.0,9.0,7.0,8.0,10.0,Male,24,Other (Please Specify):Vietnam,Bachelors
105,62a34991b4da29969c62ff4b,2022-06-10,0:01:15,Student/Looking/None,Yes,0-40k,Healthcare,Python,3.0,7.0,7.0,7.0,2.0,Male,31,United States,Masters
106,62a349bbf8f756164585400d,2022-06-10,0:02:07,Data Analyst,Yes,41k-65k,Other (Please Specify):Supply Chain - warehous...,Other:Knowledge of Excel and SQL yet,3.0,6.0,6.0,6.0,4.0,Male,25,Canada,Bachelors
107,62a349c7cec54911e9ca67c7,2022-06-10,0:01:05,Data Analyst,Yes,106k-125k,Finance,Python,5.0,1.0,4.0,3.0,4.0,Female,38,United States,Bachelors
108,62a349d5d8c00e9f5419ead2,2022-06-10,0:01:32,Data Analyst,No,41k-65k,Finance,Python,5.0,5.0,5.0,5.0,5.0,Male,30,Other (Please Specify):Netherlands,Bachelors
109,62a349e6b4da29969c63000c,2022-06-10,0:01:32,Data Analyst,Yes,0-40k,Tech,C/C++,0.0,0.0,0.0,2.0,5.0,Male,25,India,Bachelors
110,62a34a03cec54911e9ca6869,2022-06-10,0:01:08,Data Analyst,Yes,0-40k,Tech,Python,1.0,2.0,1.0,5.0,6.0,Female,29,Other (Please Specify):Nigeria,Bachelors
111,62a34ab15d257a28a30d9589,2022-06-10,0:04:27,Data Scientist,Yes,150k-225k,Finance,Python,7.0,5.0,3.0,6.0,4.0,Male,21,Other (Please Specify):Portugal,Masters
112,62a34abc0f8c8599d5af31c5,2022-06-10,0:02:00,Data Analyst,Yes,66k-85k,Other (Please Specify):Distribution,Other:SQL,5.0,8.0,8.0,7.0,7.0,Female,39,United States,Bachelors
113,62a34b07cec54911e9ca6b6e,2022-06-10,0:01:19,Student/Looking/None,No,0-40k,Other (Please Specify),Python,0.0,0.0,0.0,0.0,5.0,Male,25,Other (Please Specify):turkey,Bachelors
114,62a34b0eb4da29969c6302ce,2022-06-10,0:02:36,Other (Please Specify):Does a social media ana...,Yes,86k-105k,Finance,Other:I don't use programming in my role,7.0,9.0,10.0,6.0,4.0,Female,42,United States,Masters
115,62a34b1b0f8c8599d5af328b,2022-06-10,0:00:48,Data Analyst,No,41k-65k,Tech,R,10.0,8.0,9.0,10.0,10.0,Male,25,United States,Bachelors
116,62a34b5b5d257a28a30d96a6,2022-06-10,0:01:20,Data Scientist,No,86k-105k,Finance,Python,8.0,7.0,6.0,6.0,9.0,Male,22,United States,Bachelors
117,62a34b7ebae91e4b8b83076c,2022-06-10,0:02:04,Data Analyst,No,0-40k,Other (Please Specify):Customer Service,Python,1.0,4.0,4.0,3.0,5.0,Male,23,Other (Please Specify):Colombia,High School
118,62a34b99cec54911e9ca6e14,2022-06-10,0:02:36,Data Engineer,Yes,41k-65k,Other (Please Specify):Ecom,JavaScript,6.0,6.0,6.0,6.0,6.0,Male,25,Other (Please Specify):Egypt,High School
119,62a34bb0f3072dd892624210,2022-06-10,0:01:05,Data Engineer,Yes,66k-85k,Other (Please Specify):Consulti,Python,5.0,7.0,7.0,6.0,7.0,Male,45,Canada,Masters
120,62a34bd0cf2555431730208b,2022-06-10,0:01:29,Data Analyst,Yes,66k-85k,Healthcare,Other:Excel/SQL,7.0,3.0,8.0,6.0,8.0,Male,24,United States,Bachelors
121,62a34bd4f408bae018ed57bd,2022-06-10,0:03:57,Student/Looking/None,No,0-40k,Other (Please Specify):State Government,R,1.0,9.0,6.0,0.0,0.0,Male,25,United States,NaN
122,62a34c66b4da29969c6305af,2022-06-10,0:01:36,Data Analyst,Yes,66k-85k,Other (Please Specify):Marketing,Python,9.0,8.0,9.0,9.0,8.0,Male,26,United States,Bachelors
123,62a34d1ff8f756164585465c,2022-06-10,0:01:41,Data Analyst,No,41k-65k,Tech,R,4.0,7.0,8.0,8.0,7.0,Male,23,Canada,Bachelors

# Perform Cleaning if others are specified

In [15]:
print(df['Job Title'].unique())

['Data Analyst' 'Data Engineer'
 'Other (Please Specify):Analytics Consultant ' 'Data Scientist'
 'Student/Looking/None' 'Other (Please Specify):FP&A Analyst'
 'Other (Please Specify):BI Developer '
 'Other (Please Specify):Manager, Business Intelligence Develop'
 'Other (Please Specify):Business Analyst '
 'Other (Please Specify):Business Analyst'
 'Other (Please Specify):Business Intelligence Consultant'
 'Other (Please Specify):Sr. Supply Chain Analyst '
 'Other (Please Specify):Business analyst '
 'Other (Please Specify):Director of Data Analytics'
 'Other (Please Specify):Learning Management Specialist'
 'Other (Please Specify):Research Analyst'
 'Other (Please Specify):Insights analyst'
 'Other (Please Specify):Does a social media analyst count?'
 'Other (Please Specify):Educator'
 'Other (Please Specify):Business Intelligence Engineer'
 'Other (Please Specify):Research Associate '
 'Other (Please Specify):Analytics Manager'
 'Other (Please Specify):Manager of a team of Data Analysts'
 'Other (Please Specify):Analyst'
 'Other (Please Specify):Analytics Engineer'
 'Other (Please Specify):Analyst Primary Market Intelligence'
 'Other (Please Specify):software engineer' 'Data Architect'
 'Other (Please Specify):Data Integrity' 'Database Developer'
 'Other (Please Specify):Financial Analyst'
 'Other (Please Specify):Database Manager'
 'Other (Please Specify):Software Developer '
 'Other (Please Specify):Tableau admin' 'Other (Please Specify)'
 'Other (Please Specify):Reporting Adm'
 'Other (Please Specify):Billing analyst'
 'Other (Please Specify):I work with data tools and can create simple dashboards but I am not a data scientist'
 'Other (Please Specify):Marketing Data Specialist'
 'Other (Please Specify):Jr. Data Scientist'
 'Other (Please Specify):Continuous Quality Improvement Specialist'
 'Other (Please Specify):PMO'
 'Other (Please Specify):System Administrator'
 'Other (Please Specify):Teacher' 'Other (Please Specify):Consultant'
 'Other (Please Specify):Business Intelligence Developer'
 'Other (Please Specify):Informatics Specialist'
 'Other (Please Specify):Business Analys'
 'Other (Please Specify):Finance Analyst '
 'Other (Please Specify):Web Developer' 'Other (Please Specify):Manager '
 'Other (Please Specify):Junior Software Engineer'
 'Other (Please Specify):Researchers '
 'Other (Please Specify):Senior Business Analyst'
 'Other (Please Specify):Data Coordinator'
 'Other (Please Specify):Student working as a data analyst intern '
 'Other (Please Specify):Driver' 'Other (Please Specify):Data manager'
 'Other (Please Specify):GIS Analyst '
 'Other (Please Specify):Business Intelligence Analyst'
 'Other (Please Specify):BI consultant ' 'Other (Please Specify):DBA'
 'Other (Please Specify):Data Steward'
 'Other (Please Specify):Technical consulta'
 'Other (Please Specify):Software Engineer, AI '
 'Other (Please Specify):Systems configuration '
 'Other (Please Specify):Sales & marketing'
 'Other (Please Specify):RF Engineer'
 'Other (Please Specify):Support Engineer'
 'Other (Please Specify):Account manager'
 'Other (Please Specify):Incident Manager'
 'Other (Please Specify):Product owner'
 'Other (Please Specify):Presales Engineer '
 'Other (Please Specify):Predictive Analyst'
 'Other (Please Specify):Ads operations'
 'Other (Please Specify):Power Bi Developer'
 'Other (Please Specify):Software support'
 'Other (Please Specify):Investigation specialist'
 'Other (Please Specify):Director' 'Other (Please Specify):Data Manager'
 'Other (Please Specify):SAP Security Analyst'
 'Other (Please Specify):BI Manager'
 'Other (Please Specify):Data Scientist Intern']

In [16]:
df['Job Title'] = df['Job Title'].apply(lambda x: x.split(':', 1)[-1].strip() if ':' in x else x)

df['Working Industry'] = df['Working Industry'].apply(lambda y: y.split(':', 1)[-1].strip() if ':' in y else y)

df['Favorite Programming Language'] = df['Favorite Programming Language'].apply(lambda z: z.split(':', 1)[-1].strip() if ':' in z else z)

df['Country'] = df['Country'].apply(lambda s: s.split(':', 1)[-1].strip() if ':' in s else s)

# Modify Salary Column: Create Average Salary Column

In [17]:
print(df['Annual Salary (USD)'].unique())

['106k-125k' '41k-65k' '0-40k' '150k-225k' '125k-150k' '86k-105k'
 '66k-85k' '225k+']

In [18]:
df[['Min Annual Salary', 'Max Annual Salary']] = df['Annual Salary (USD)'].str.split('-', expand=True)

df['Min Annual Salary'] = df['Min Annual Salary'].str.replace('k', '000').str.replace('+', '').astype(float)
df['Max Annual Salary'] = df['Max Annual Salary'].str.replace('k', '000').str.replace('+', '').astype(float)

df['Average Annual Salary'] = (df['Min Annual Salary'] + df['Max Annual Salary']) / 2

C:\Users\TALIYEVA\AppData\Local\Temp\ipykernel_28136\1155939946.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Min Annual Salary'] = df['Min Annual Salary'].str.replace('k', '000').str.replace('+', '').astype(float)
C:\Users\TALIYEVA\AppData\Local\Temp\ipykernel_28136\1155939946.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Max Annual Salary'] = df['Max Annual Salary'].str.replace('k', '000').str.replace('+', '').astype(float)

In [19]:
print(df[df['Annual Salary (USD)'] == '225k+'])

                    Unique ID Date Taken (America/New_York) Time Spent  \
379  62a477f0b4da29969c64892f                    2022-06-11    0:01:04
454  62a56bc67dc029e2d66e86c0                    2022-06-12    0:01:37

          Job Title Career Switch to Data Annual Salary (USD)  \
379  Data Scientist                   Yes               225k+
454   Data Engineer                   Yes               225k+

    Working Industry Favorite Programming Language  Happy with salary  \
379             Tech                             R                5.0
454             Tech                           Sql                3.0

     Happy with work-life balance  Happy with coworkers  \
379                           6.0                   5.0
454                           3.0                   4.0

     Happy with management  Happy with learning opportunities Gender  Age  \
379                    5.0                                6.0   Male   31
454                    4.0                                5.0   Male   33

           Country Level of Education  Min Annual Salary  Max Annual Salary  \
379  United States                PhD           225000.0                NaN
454  United States          Bachelors           225000.0                NaN

     Average Annual Salary
379                    NaN
454                    NaN

In [20]:
df['Max Annual Salary'].fillna(225000.0, inplace=True)

df['Min Annual Salary'].replace(225000.0, 0.0, inplace=True)

df['Average Annual Salary'].fillna(112500.0, inplace=True)

# Loop through "favorite programming language" column (answers given were a bit messy)

In [21]:
programming_languages = ['Python', 'R', 'SQL', 'JavaScript', 'C/C++', 'C#', 'Excel', 'Java', 'SAS', 'VBA', 'MATLAB', 'Php']

for index, entry in df['Favorite Programming Language'].items():
    for lang in programming_languages:
        if lang.lower() in entry.lower():
            df.loc[index, 'Favorite Programming Language'] = lang
            break

In [22]:
# assign null entries to be just empty

df['Level of Education'] = df['Level of Education'].fillna('')

In [27]:
print(df['Job Title'].unique())

['Data Analyst' 'Data Engineer' 'Analytics Consultant' 'Data Scientist'
 'Student/Looking/None' 'FP&A Analyst' 'BI Developer'
 'Manager, Business Intelligence Develop' 'Business Analyst'
 'Business Intelligence Consultant' 'Sr. Supply Chain Analyst'
 'Business analyst' 'Director of Data Analytics'
 'Learning Management Specialist' 'Research Analyst' 'Insights analyst'
 'Does a social media analyst count?' 'Educator'
 'Business Intelligence Engineer' 'Research Associate' 'Analytics Manager'
 'Manager of a team of Data Analysts' 'Analyst' 'Analytics Engineer'
 'Analyst Primary Market Intelligence' 'software engineer'
 'Data Architect' 'Data Integrity' 'Database Developer'
 'Financial Analyst' 'Database Manager' 'Software Developer'
 'Tableau admin' 'Other (Please Specify)' 'Reporting Adm'
 'Billing analyst'
 'I work with data tools and can create simple dashboards but I am not a data scientist'
 'Marketing Data Specialist' 'Jr. Data Scientist'
 'Continuous Quality Improvement Specialist' 'PMO' 'System Administrator'
 'Teacher' 'Consultant' 'Business Intelligence Developer'
 'Informatics Specialist' 'Business Analys' 'Finance Analyst'
 'Web Developer' 'Manager' 'Junior Software Engineer' 'Researchers'
 'Senior Business Analyst' 'Data Coordinator'
 'Student working as a data analyst intern' 'Driver' 'Data manager'
 'GIS Analyst' 'Business Intelligence Analyst' 'BI consultant' 'DBA'
 'Data Steward' 'Technical consulta' 'Software Engineer, AI'
 'Systems configuration' 'Sales & marketing' 'RF Engineer'
 'Support Engineer' 'Account manager' 'Incident Manager' 'Product owner'
 'Presales Engineer' 'Predictive Analyst' 'Ads operations'
 'Power Bi Developer' 'Software support' 'Investigation specialist'
 'Director' 'Data Manager' 'SAP Security Analyst' 'BI Manager'
 'Data Scientist Intern']

# Convert dataframe to excel file

In [25]:
df.to_excel(r"C:\Users\TALIYEVA\01_Project_Data_Analysts_Survey\Cleaned_Survey_Dataset.xlsx", index = False, sheet_name = 'Survey Data')